config/routes.rb
Upgrade::Application.routes.draw do
  match '/' => 'users#login'

  resources :users do
    collection do
  get :login
  post :login
  get :changepassword
  post :changepassword
  get :logout
  get :emailcheck
  get :tasks_catagory
  end
  end
  resources :tasks do
    collection do
  put :update_task_progess
  post :share_task
  get :share_name_display
  put :changeorder_up
  put :changeorder_down
  get :search_task
  end
  end
  resources :users do
      resources :tasks do
          resources :comments
    end
  end
  resources :tasks do
      resources :comments
  end
  match '/:controller(/:action(/:id))'
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  has_many:comments, :dependent => :destroy
  validates_length_of :task, :minimum => 1, :allow_blank => false
  has_many:tags, :dependent => :destroy
  after_create :create_tag
  attr_accessible :task,:status,:task_progress

  private
       def create_tag
         @tag=Tag.new()
         @tag.task_id=id
         @task=Task.find(id)
         @id=@task.user_id
         @tag.user_id=@id
         @tag.task_order=id
         @tag.save
       end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :check_id
@task_progres=[]

def create
    @task = Task.new(params[:task])
    @task[:status]=0;
    @task[:user_id]=session[:user_id]
  if @task.save
    render_tasks()
  else
     flash[:notice] = @task.errors
     redirect_to :controller=>'tasks',:action=>"index"
  end

end

def index
  @u_id=session[:user_id]
  if (params[:status]=="1")
    @tasks=Task.paginate(:page=>params[:page],:per_page=>5,:select=>"tasks.*,tags.task_order",:joins=>:tags,:conditions=>["tags.user_id=? and status=1",@u_id],:order=>"tags.task_order DESC")
  else
    @tasks=Task.paginate(:page=>params[:page],:per_page=>5,:select=>"tasks.*,tags.task_order",:joins=>:tags,:conditions=>["tags.user_id=? and status=0",@u_id],:order=>"tags.task_order DESC")
  end
end
def destroy
    @u_id=session[:user_id]
    @d_id=params[:id]
    Task.destroy(@d_id)
    render_tasks()
end

def new
    @user=User.first
    @task = Task.new
end

def changeorder_down
  @u_id=session[:user_id]
  current_task_id=params[:task][:task_id].to_i
  current_task_row=Tag.find(:first,:conditions=>{:task_id=>current_task_id,:user_id=>@u_id})
  current_task_order=current_task_row.task_order
  next_task=Tag.find(:last,:conditions=>"task_order < #{current_task_order} and user_id=#{@u_id}")
  next_task_order=next_task.task_order
  next_task_id=next_task.id
  current_task_row.update_attributes(:task_order=>next_task_order)
  next_task.update_attributes(:task_order=>current_task_order)
  render_tasks()
end
def changeorder_up
  @u_id=session[:user_id]
  current_task_id=params[:task][:task_id].to_i
  current_task_row=Tag.find(:first,:conditions=>{:task_id=>current_task_id,:user_id=>@u_id})
  current_task_order=current_task_row.task_order
  next_task=Tag.find(:first,:conditions=>"task_order > #{current_task_order} and user_id=#{@u_id}")
  next_task_order=next_task.task_order
  next_task_id=next_task.id
  current_task_row.update_attributes(:task_order=>next_task_order)
  next_task.update_attributes(:task_order=>current_task_order)
  render_tasks()
end

def update
  @u_id=session[:user_id]
  t=Task.find(params[:id])
  if t.user_id==@u_id
      if t.status==0
         Task.find(params[:id]).update_attributes(:status=>1)
         @tasks=Task.paginate(:page=>params[:page],:per_page=>5,:select=>"tasks.*,tags.task_order",:joins=>:tags,:conditions=>["tags.user_id=? and status=0",@u_id],:order=>"tags.task_order DESC")
         @comment= Comment.new()
         @comment[:task_id]=params[:id]
         @comment[:user_id]=session[:user_id]
         sleep(1)
         @comment[:body]="Status  of the task changed to <span class='c'>Done</span>"
         @comment.save
         render :partial => "taskcontent"
      else
         Task.find(params[:id]).update_attributes(:status=>0)
         @tasks=Task.paginate(:page=>params[:page],:per_page=>5,:select=>"tasks.*,tags.task_order",:joins=>:tags,:conditions=>["tags.user_id=? and status=1",@u_id],:order=>"tags.task_order DESC")
         render :partial => "taskcontent"
      end
  end
end
def show
      @u_id=session[:user_id]
      @user=User.find(params[:user_id])
      @task=Task.find(params[:id])
      @task_id=@task.id;
      @users=User.all
      @assigned_users=Tag.find_all_by_task_id(params[:id]).collect(&:user_id)
      @share_check=Task.find(:all,:conditions=>"id=#{params[:id]}")
      @shares=Tag.find(:all,:conditions=>"task_id=#{params[:id]}")
      @comments=@task.comments
end
def update_task_progess
  @current_task_progres=params[:task][:task_range].to_i
  @u=Task.find(params[:task][:task_id].to_i)
  @previous_task_progres=@u.task_progress
  if @current_task_progres > @previous_task_progres and @u.status==0
    if @u.update_attributes(:task_progress=>@current_task_progres)
      @comment= Comment.new()
      @comment[:task_id]=params[:task][:task_id].to_i
      @comment[:user_id]=session[:user_id]
      @comment[:body]="Task has been update from <span class='c'>#{@previous_task_progres}%</span> to <span class='c'> #{@u.task_progress}%</span> "
        if @comment.save
          @comments=Comment.find_all_by_task_id(params[:task][:task_id].to_i)
          render :partial => "tasks/commentlist"
        end
    end
  else
        @comments=Comment.find_all_by_task_id(params[:task][:task_id].to_i)
        render :partial => "tasks/commentlist"
       
  end
end
def share_task
  @share_user_id=params[:share_names]
  @delete_status=Tag.destroy_all(:task_id => params[:task_id])
  @name_size=@share_user_id.length;

    if @delete_status
      @tag=Tag.new()
      @tag[:user_id]=@u_id
      @tag[:task_id]=params[:task_id]
      @tag[:task_order]=params[:task_id]
      @tag.save
        for i in 0..(@name_size-1)
            @tag=Tag.new()
            @tag[:user_id]=@share_user_id[i]
            @tag[:task_id]=params[:task_id]
            @tag[:task_order]=params[:task_id]
            @tag.save
        end
          @shares=Tag.find(:all,:conditions=>"task_id=#{params[:task_id]}")
          render :partial => "sharenames"
    end
  end

def search_task
  search_keyword=params[:task][:task_name].to_s
  if search_keyword
  @tasks =Task.paginate(:page=>params[:page],:per_page=>5,:select=>"tasks.*,tags.task_order",:joins=>:tags,:conditions=>["tags.user_id=? and task  LIKE ?",@u_id ,"%#{search_keyword}%"],:order=>"tags.task_order DESC")
  sleep(3)
  render :partial => "/tasks/taskcontent"
  else
    sleep(3)
    @tasks=Task.all.paginate(:page=>params[:page],:per_page=>5,:select=>"tasks.*,tags.task_order",:joins=>:tags,:conditions=>["tags.user_id=? ",@u_id],:order=>"tags.task_order DESC")
  end
end


def share_name_display
  @users=User.all
  @assigned_users=Tag.find_all_by_task_id(params[:task][:task_id]).collect(&:user_id)
  if @task_owner_id=@assigned_users
      render :partial => "sharetaskmodal"
  else
      render :partial => "sharetaskmodal"
  end
end




private

def check_id
  p "-------------------------------------------"
  p session[:user_id]
if session[:user_id].nil?
  redirect_to :controller=>'users',:action=>"login"
else
  @user=User.find(session[:user_id])
  @u_id=session[:user_id]
  @tasks=Task.all.paginate(:page=>params[:page],:per_page=>5,:select=>"tasks.*,tags.task_order",:joins=>:tags,:conditions=>["tags.user_id=? and status=0",@u_id],:order=>"tags.task_order DESC")
end
return true
end
 def render_tasks
     @u_id=session[:user_id]
     @tasks=Task.paginate(:page=>params[:page],:per_page=>5,:select=>"tasks.*,tags.task_order",:joins=>:tags,:conditions=>["tags.user_id=? and status=0",@u_id],:order=>"tags.task_order DESC")
     render :partial => "taskcontent"
 end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_commentlist.erb
<% @comments.each do |c| %> <p>
    <div class="div_task" style="margin-bottom:-12px;margin-top:-10px; padding: 20 20 0;width: 592px; border:none;">
      <p style="margin-bottom:1px;">
            </b> <%= raw(c.body) %> </p>
      <p style="margin-bottom:1px;">
              <p style="font-size: 16px"><%=h c.user.name%> <span id="comment_span"> on <%=(c.created_at).strftime("%I.%P,  %d %b %Y")%></span></p>
             </hr>
    </div>
  
<% end %>

app/views/tasks/_sharenames.erb
<% shared_with = [] %>
<% @shares.each do |s| %>
    <% shared_with.push(s.user.name) if (s.user and (s.user.name!=@user.name))%>
<% end %>

<span id="comment_span"> Shared with: </span>
<%= shared_with.join(" ,  ")%>
</p>

app/views/tasks/_sharetaskmodal.erb
<%form_for :shares_form do |s|%>
<table>
  <tr>
<% @users.each do |user| %>
      <% if  user.name!=@user.name%>
           <td style="padding-left: 5px"><%= check_box_tag "share_names[]",user.id,@assigned_users.include?(user.id)%>  </td>
         <td  style="padding-left: 10px;padding-right: 89px;"><%=user.name%></td>
      <% end %>
  <% end %>
  </tr>
    <%= javascript_include_tag "modal_jss" %>
</table>
<% end %>

app/views/tasks/_taskcontent.erb
<link href='http://fonts.googleapis.com/css?family=Open+Sans:700,300' rel='stylesheet' type='text/css'>
<%= javascript_include_tag "taskscript" %>
<%unless @tasks.nil?%>
<% @tasks.each do |task| %>
    <div id="task_<%=task.id %>" class="div_task" >
          <div id="dispaly_text_div">
            <p id="c"><%=link_to "#{task.task}",user_task_path(@u_id,task),:style => "font-size: 16px;color: #34495e"%>
              <br>
            <p style="word-wrap: break-word;color:#ccc;font-size: 12px;margin-bottom:8px;"> By <%= (task.user.name)%></p>
            </p>
            <p style="word-wrap: break-word;color:#ccc;font-size: 12px;margin-bottom:8px;"><%=(task.created_at).strftime("%I.%P,  %d %b %Y")%></p>
            <p>
            </p>
          </div>
          <div id="icon_img">
                    <%if task.status==0 %>
                        <button class="img_up" onclick="image_up(<%=task.id %>)" data-id=<%=task.id %> data-user_id=<%=task.user_id%>></button>
                        <button class="img_down" onclick="image_down(<%=task.id %>)" data-id=<%=task.id %> data-user_id=<%=task.user_id%>></button>
                    <%end%>
                    <button class="img_close" onclick="delete_req(<%=task.id %>)" data-id="<%=task.id %>" data-user_id=<%=task.user_id%>></button>

                    <%if(task.status==0) %>
                        <button class="img_done" onclick="image_done(<%=task.id %>,<%=task.user_id %>)" data-id=<%=task.id %> data-user_id=<%=task.user_id%>> </button>
                    <%else%>
                        <button class="img_ok" onclick="image_ok(<%=task.id %>,<%=task.user_id %>)" data-id=<%=task.id %> data-user_id=<%=task.user_id%>> </button>
                    <%end%>
                    <!--delete div-->
                    <div class="delete_div" id="delete_<%= task.id %>">
                    <p id="delete_text">Are you sure you want to delete this entry ?</p>
                    <div class="pull-right">
                    <button id="delete_task "  style="margin-top: -182px;width: 79px;" onclick="delete_task(<%=task.user_id%>,<%= task.id %>)">Yes</button>
                    <button id="cancel_delete" onclick="cancel_delete(<%=task.id %>)">No</button>
              </div>
            </div>
          </div>
        </div>
<%end%>
<%end%>
<%= will_paginate @tasks, :id=>'page-nav' %>
<%= javascript_include_tag "masonry" %>
<%= javascript_include_tag "jquery.infinitescroll" %>

app/views/tasks/delete.html.erb
<h1>Tasks#delete</h1>
<p>Find me in app/views/tasks/delete.html.erb</p>

app/views/tasks/index.html.erb
<%= javascript_include_tag "scroll" %>
<link href='http://fonts.googleapis.com/css?family=Open+Sans:700,300' rel='stylesheet' type='text/css'>
<%unless flash[:notice_login].nil?%>
<div class="alert alert-success" style="position:fixed;top:5px;">
 <a class="close" data-dismiss="alert">×</a>
     <%=flash[:notice_login] %>
</div>
<%end%>
<div id="text_area">
  <div id="img_textbox"></div>
  <input id="textbox1"  type="text" name="task" placeholder="Add your todo entry  Hit 'Enter' to post "/>
  </p>
</div>

<div >
<% unless @tasks.empty?%>
  <%if @tasks.first.status==0%>
      <a id="active"  style="background-color: #e8e8e8" href="/tasks?status=0">Active</a>
      <a id="inactive" href="/tasks?status=1">Inactive</a>
  <%elsif @tasks.first.status==1%>
      <a id="active"  href="/tasks?status=0">Active</a>
      <a id="inactive" style="background-color: #e8e8e8" href="/tasks?status=1">Inactive</a>
  <%else%>
      <a id="active"  style="background-color: #e8e8e8" href="/tasks?status=0">Active</a>
      <a id="inactive" href="/tasks?status=1">Inactive</a>
  <%end%>
<%end%>
</div>
<div id="content_area">
  <%= render :partial => "taskcontent"  %>
</div>

app/views/tasks/show.html.erb
<%= stylesheet_link_tag "bootstrap" %>
<%= stylesheet_link_tag "todo_css" %>
<%= javascript_include_tag "modal_jss" %>
<%= javascript_include_tag "taskscript" %>
<%= javascript_include_tag "flat-ui" %>
<%= stylesheet_link_tag "bootstrap" %>
<%= stylesheet_link_tag "flat-ui" %>
<%= javascript_include_tag "taskscript" %>
<%= stylesheet_link_tag "bootstrap" %>
<%= javascript_include_tag "taskscript" %>
<%= javascript_include_tag "modal_jss" %>
<%= javascript_include_tag "bootstrap" %>
<%= javascript_include_tag "slider" %>
<script>
    $(function() {
        $( "#slider" ).slider();
    });
</script>
<div>
  <div class="modal" id="basicModal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true" >
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title"  style="font-family: 'open sans';font-weight: 100;font-size: 20px" id="myModalLabel">Add people to do this task</h4>
        </div>
        <div class="modal-body" style="font-family: 'open sans';font-weight: 100;font-size: 14px" id="modal-body" style="font-size: 16px !important;">
          <h3> <%= render :partial => "sharetaskmodal"  %></h3>
        </div>
        <div class="modal-footer" style="background-color:#ffffff">
          <button type="button" class="save_button" data-dismiss="modal" style="position:relative !important;" onclick="share_task(<%=@task.id%>)">Save</button>
          <button type="button" class="cancel_button" data-dismiss="modal">cancel</button>

        </div>
      </div>
    </div>
  </div>
  <div id="back_button">
    <%=link_to "< Go back to home",tasks_path,:style => "color: #34495e"%>
  </div>
  <div id="comment_hedder">


    <div class="modal fade" id="myModal">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title">Delete Task</h4>
          </div>
          <div class="modal-body">
            <p>Are you sure you want to delete this entry?&hellip;</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal"  onclick="cancel_delete(<%=params[:id] %>)"><u>No</u></button>
            <button type="button" class="btn btn-primary" onclick="delete_task(<%=params[:user_id]%>,<%= params[:id] %>)">Yes</button>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
       <div id="task_data">
      <p style="font-size:24px;margin-bottom: 10px">
        <%=@task.task %>
       
      </p>
      <p style="word-wrap: break-word;color:#ccc;font-size: 14px;margin-bottom:-5px;"> <span>  <%= (@task.user.name)%><br></span>  <%=(@task.created_at).strftime("%I.%P,%d %b %Y")%></p>
      <button  style="margin-top: -90px;margin-left: 585px;" data-toggle="modal" data-target="#myModal" class="img_close"></button>
    </div>
    <p style="font-size:16px">Task completion</p>
    <div id="slider" data-id="<%= params[:id] %>" data-progress_id="<%=@task.task_progress%>" style="height: 20px;border-radius: 0px;width: 92%">
      <%if(@task.status==0) %>
          <button  id="done" class="img_done" onclick="image_comment_done(<%=@task.id %>,<%=@task.user_id%>)" data-id=<%=@task.id %> data-user_id=<%=@task.user_id%> style="margin-top: -9;margin-left: 564px;"> </button>
      <%else%>
    <script>
      $( "#slider" ).slider({
             disabled: true
      });
    </script>
          <button id="ok"  class="img_ok" onclick="image_comment_ok(<%=@task.id %>,<%=@task.user_id %>)" data-id=<%=@task.id %> data-user_id=<%=@task.user_id%> style="margin-top: -9;margin-left: 564px;"> </button>
      <%end%>
    </div>
    <div id="task_share">
      <p style="font-size:12px;margin:5px 0px 5px  20 ">
      <div id="share_div_partials">
        <%= render :partial => "sharenames"  %>
      </div>
      <% if (@share_check.first.user_id==@u_id)%>
          <input type="button"  id="share_button" data-toggle="modal" data-target="#basicModal" value="share this" onclick="share_task_name_dispaly(<%=@task.id%>)">
      <%end%>
    </div>
  </div>
  <div id="comment_partial_div">
    <%= render :partial => "commentlist"  %>
  </div>
  <div>
    <input id="comment_box"  type="text" name="task" placeholder="Add the comment  Hit 'Enter' to post " data-task_id="<%=@task.id%>"/>
  </div>
</div>